### ISSUE TITLE
Is README.md broken

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdp#47]
@doutriaux1 When I open https://github.com/CDAT/cdp, I'm not sure the README looks exactly right (badge and status stuff). See screenshot below

![cdp_readme](https://user-images.githubusercontent.com/2785573/48493040-5f9a8500-e82b-11e8-9584-c568a87f6efd.png)

**Comment by zshaheen** [comment]
@jypeter Let me fix that...

**Comment by zshaheen** [comment]
Thanks for noticing that, it's fixed now. If you feel like anything should be added or changed, feel free to open this or another issue.

<img width="995" alt="screen shot 2018-11-14 at 7 47 51 am" src="https://user-images.githubusercontent.com/4239938/48493899-9d72bb80-e7e1-11e8-84e6-a567aef12122.png">
