### ISSUE TITLE
cdp and how to install pcmdi_metrics cleanly in cdat 8.0

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdp#48]
@zshaheen A question about **pcmdi_metrics** now, because I don't know where I should ask this

I have installed (at last!) **cdat 8.0** the following way
`conda create -n cdat-8.0_py2 -c cdat/label/v80 -c conda-forge -c cdat python=2.7 cdat`
and I automatically got
`cdp                       1.2.3            py27hf758207_0    cdat/label/v80`

Now if I wonder what's the correct way to add **pcmdi_metrics**. Not because I'm actually using it, but because it was installed in my old cdat 2.10 and I'm trying to have a similar setup. I'm not sure where _installing pcmdi_metrics_ is described. I confess I don't actually need cdp either. But I'm reporting _things_ related to cdp in my installation process

Anyway, I have tried 2 different installation command lines. The first line does not complete and mentions another version of cdp

```
 >conda install -n cdat-8.0_py2 -c pcmdi pcmdi_metrics
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pcmdi_metrics
  - cdp[version='>=1.4.0']

```

If I add the cdat channel, I get a bunch of install/upgrades, including an upgrade of cdp. Is this the correct way to do things? I'm not really used to specifying channels and versions/labels. The output below does not change if I add `-c cdat/label/v80`
```
 >conda install -n cdat-8.0_py2 -c cdat -c pcmdi pcmdi_metrics
Solving environment: done

## Package Plan ##

  environment location: /home/share/unix_files/cdat/miniconda3/envs/cdat-8.0_py2

  added / updated specs:
    - pcmdi_metrics


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pcmdi_metrics-1.2          |   py27h39e3cac_0         1.6 MB  pcmdi
    cdp-1.4.1                  |           py27_0          27 KB  cdat
    output_viewer-1.2.5        |           py27_0         100 KB  cdat
    cia-0.0.6                  |                0           4 KB  pcmdi
    ------------------------------------------------------------
                                           Total:         1.7 MB

The following NEW packages will be INSTALLED:

    cia:           0.0.6-0              pcmdi
    pcmdi_metrics: 1.2-py27h39e3cac_0   pcmdi

The following packages will be UPDATED:

    cdp:           1.2.3-py27hf758207_0 cdat/label/v80 --> 1.4.1-py27_0 cdat
    output_viewer: 1.2.3-py27h48dab56_0 cdat/label/v80 --> 1.2.5-py27_0 cdat

Proceed ([y]/n)? ^C
```

**Comment by doutriaux1** [comment]
@jypeter pcmdi_metrics question should addressed [here](https://github.com/PCMDI/pcmdi_metrics/issues)

But it seems like you found the correct installation command.
